spring.application.name=authService
server.port=8070
server.address=localhost


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=gday2051001~

spring.datasource.username=postgres
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=20MB

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.use_sql_comments= true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



# JWT
jwt.secret-key=bL2qC3bO1gC2fI1cK4vB3oI3cG4bK3cG4qC2nH1fC6eL3
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG

